### ISSUE TITLE
Create Group E Transaction Screen (JF Transfers)

### ISSUE THREAD

**Issue by AureliaKhorsand** [fecgov/fecfile-web-app#233]
Business Reason 
 

As a Committee Administrator, I will be able to enter a transaction for **"JF Transfers"** on Schedule A of a Form 3X report so that I can accurately report on my committee's transactions.

**NOTE:** This is a "parent" transaction that will typically have associated sub-transactions.

 Acceptance Criteria 
 

**Given** I am a Committee Administrator editing an open Form 3X report
**When** I Add a new transaction
**And** click(open) on the "Transfers" accordion link
**Then** I can enter a transaction with the type "JF Transfers"
**And** I will be required to enter the following information (unless otherwise noted):

# Contributor 
#
-	**CONTRIBUTOR TYPE** (Read-only)
Field description in API: ENTITY TYPE
Data field: COMMITTEE
-	**COMMITTEE NAME** (A/N-200, Required)
Field description in API: CONTRIBUTOR ORGANIZATION NAME
Data field: textbox
-	**CONTRIBUTOR FEC ID** (A/N-9, Required)
Field description in API: DONOR COMMITTEE FEC ID
Data field: textbox
With the ID in the following format: "CXXXXXXXX" where X is a numeric value _(C, then 8 numbers)_
**FEC ID IS A STOP-GAP UNTIL THE LOOKUP IS IN PLACE**
<br>

# Address 
#
-	**STREET ADDRESS** (A/N-34, Required)
Field description in API: CONTRIBUTOR STREET 1
Data field: textbox
-	**APARTMENT, SUITE, ETC.** (A/N-34, Optional)
Field description in API: CONTRIBUTOR STREET 2
Data field: textbox
-	**CITY** (A/N-30, Required)
Field description in API: CONTRIBUTOR CITY
Data field: textbox
-	**STATE/PROVINCE** (ALPHA-2, Required)
Field description in API: CONTRIBUTOR STATE
Data field: Dropdown
          Dropdown options: States without military
          https://docs.google.com/spreadsheets/d/17YmnaZgqvFOUyv4-Qknd8ikHe8o9LoDb/edit#gid=494776297
-	**ZIP/POSTAL CODE** (A/N-9, Required)
Field description in API: CONTRIBUTOR ZIP
Data field: textbox
<br>

# Contribution 
#
-	**DATE RECEIVED** (NUM-8…YYYYMMDD, Required)
Field description in API: CONTRIBUTION DATE
Data field: Date picker 
-	**MEMO ITEM** (A/N-1, Optional)
Field description in API: MEMO CODE
Data field: Checkbox
-	**CONTRIBUTION AMOUNT** (AMT-12, Required)
Field description in API: CONTRIBUTION AMOUNT
Data field: textbox
-	**CONTRIBUTION AGGREGATE** (AMT-12, Required)
Field description in API: CONTRIBUTION AGGREGATE
Data field: textbox (FOR NOW it will say $0.00)
This is automatically calculated as an aggregate of this contributor's contributions YTD, in any reports, in chronological order)
<br>

# Additional information 
#
-	**CONTRIBUTION PURPOSE DESCRIPTION** (Read-only)
Field description in API: RECEIPT DESCRIPTION
Data field: multi-line textbox that MUST SAY "Transfer of JF Proceeds"
-	**NOTE OR MEMO TEXT** (A/N-100, Optional)
Field description in API: MEMO TEXT/DESCRIPTION
Data field: multi-line textbox

**Then** I will be able to:

- Cancel
- Save & view all transactions
- Save & add another
- Save & add a JF Transfer Memo, which will open a new transaction screen for the sub-transaction I select (see #327)
- Edit as needed

 Dev Note 

# See Schedule A spec [here](https://fecgov.github.io/fecfile-validate/SchA_spec.html). 
#

# See JF Transfers spec [here](https://fecgov.github.io/fecfile-validate/JF_TRAN_spec.html). 
#

![Group E - JF Transfers.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/8b2f2a5c-a8ff-4b55-bd0e-4b771151bed8)

![Group E - JF Transfer - Errors.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/27290614-3f3b-4a00-8104-2f3ba4c95e7d)

![Group E - JF Transfer - Required Fields.png](https://images.zenhubusercontent.com/619e83beec2d9fadb74ad6d1/93af6cc5-7dd8-4904-bf22-8005d8b236be)

### QA Notes ### 
 null
### DEV Notes ### 
 null
### Design ### 
 null

**Comment by AureliaKhorsand** [comment]
Questions for FEC: 
1. What should the Entity type default to? Is it "Organization"? It seems like it only has one option in the specs. **Correct.**
2. How are "Donor Committee Name" and "Donor Committee ID" captured? What are these fields referring to? **Donor Committee Name will be the same as Organization Name. We should pull in the FEC ID for it if available.**

Note that Committee Organization Name can be an Organization OR Committee. Update this and #234. If it is an ORG, then we do not need the ID number. For JF Transfers specifically, it will always be a Committee.

**Comment by MitchellTCG** [comment]
@AureliaKhorsand 
Updated

**Comment by MitchellTCG** [comment]
I corrected a misspelling of TRANSFER in the orange button

**Comment by AureliaKhorsand** [comment]
@MitchellTCG to update Save & Add JF Transfer Memo button

**Comment by MitchellTCG** [comment]
@AureliaKhorsand Updated

**Comment by mjtravers** [comment]
Requesting code changes documented in the [PR](https://github.com/fecgov/fecfile-web-app/pull/358). Sending back to In Progress

**Comment by mjtravers** [comment]
Passes CR. There is still an issue with the required text warning not showing up for the date field but this will be addressed in a follow up ticket. Sending to QA

**Comment by AureliaKhorsand** [comment]
@mjtravers do you have the follow-up ticket number that will address the date field required text?

**Comment by mjtravers** [comment]
@AureliaKhorsand Here is the ticket for the missing date field required text: https://app.zenhub.com/workspaces/fecfile-online-619e578e68408b001c831251/issues/fecgov/fecfile-web-app/363

**Comment by WiseQA** [comment]
Returned to in-progress "Date Field" not showing "Required Field".   This is broken in this ticket, as it worked in Sprint 9.  QA was not aware of any defect being written on this ticket.

**Comment by WiseQA** [comment]
Note:  Wireframe and Acceptance showed:
-	**CONTRIBUTOR FEC ID** (A/N-10, Required)
Field description in API: DONOR COMMITTEE FEC ID
Data field: textbox
With the ID in the following format: "CXXXXXXXX" where X is a numeric value _(C, then 8 numbers)

After verifying requirements **CONTRIBUTOR FEC ID** (A/N-10, Required) should be A/N-9.   

Changed Acceptance criteria in #233 and #327

**Comment by WiseQA** [comment]
QA reviewed and verified Group E Transaction Screen using JF Transfers.

Test Case/Test Script attached showing ticket “PASS”.
[https://app.zenhub.com/files/306118986/5bf853b7-cd1c-4f4f-ab1f-59667524ab3a/download](https://app.zenhub.com/files/306118986/5bf853b7-cd1c-4f4f-ab1f-59667524ab3a/download)

QA review completed.  Moved to Stage Ready.
